# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tip',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
